/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        // Primary: Nunito (rounded, friendly, great for learning), Heebo as Hebrew fallback
        sans: ['Nunito', 'Heebo', 'ui-sans-serif', 'sans-serif'],
        heebo: ['Heebo', 'Nunito', 'sans-serif'],
        // Math / code: monospace stack used for all LTR formula display
        mono: ['ui-monospace', 'SFMono-Regular', 'Menlo', 'Consolas', 'monospace'],
      },
      colors: {
        'surface-container-high': '#e5e1e8',
        'surface-tint': '#675c00',
        'error': '#b02500',
        'error-container': '#f95630',
        'tertiary-fixed-dim': '#c3eb6d',
        'inverse-primary': '#fde403',
        'primary-container': '#fde403',
        'primary-fixed': '#fde403',
        'on-secondary-container': '#5400ce',
        'surface-container-low': '#f4eff5',
        'primary-fixed-dim': '#edd600',
        'on-surface-variant': '#5d5b5f',
        'secondary-fixed-dim': '#ccb9ff',
        'outline-variant': '#afacb1',
        'secondary-container': '#d9caff',
        'on-secondary': '#f7f0ff',
        'tertiary-container': '#d1fa7a',
        'tertiary-fixed': '#d1fa7a',
        'surface-bright': '#faf5fb',
        'secondary-fixed': '#d9caff',
        'on-primary-fixed-variant': '#675c00',
        'brand-primary': '#675c00',
        'on-tertiary': '#deff97',
        'on-surface': '#2f2e32',
        'on-secondary-fixed': '#3e009d',
        'secondary-dim': '#5d00e3',
        'on-primary-fixed': '#484000',
        'outline': '#78767b',
        'on-primary-container': '#5c5200',
        'on-primary': '#fff4b8',
        'on-tertiary-fixed-variant': '#4d6a00',
        'inverse-on-surface': '#9f9ca1',
        'on-tertiary-container': '#455f00',
        'on-error': '#ffefec',
        'brand-surface': '#faf5fb',
        'surface-container-highest': '#e0dbe3',
        'surface-variant': '#e0dbe3',
        'brand-secondary': '#6a1cf6',
        'surface-container-lowest': '#ffffff',
        'on-background': '#2f2e32',
        'brand-tertiary': '#496400',
        'surface-container': '#ebe7ed',
        'inverse-surface': '#0e0e11',
        'on-secondary-fixed-variant': '#5e00e6',
        'surface-dim': '#d7d3db',
        'primary-yellow': '#fde403',
      },
      keyframes: {
        'fade-up': { '0%': { opacity: '0', transform: 'translateY(16px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
        'hint-pulse': { '0%,100%': { transform: 'scale(1)' }, '50%': { transform: 'scale(1.04)' } },
      },
      animation: {
        'fade-up': 'fade-up 0.3s ease-out both',
        'hint': 'hint-pulse 0.5s ease-in-out',
      },
    },
  },
  plugins: [],
}
